# Algorithm parameters
[algorithm_params]
time_limit = 100.0
gap_tolerance = 1e-9
solver = "CPLEX"
verbose = false


# Solver specific parameters
[solver_params.master]
solver = "CPLEX"
CPX_PARAM_EPINT = 0.0
CPX_PARAM_EPGAP = 1e-9
CPX_PARAM_EPRHS = 1e-9

[solver_params.sub]
solver = "CPLEX"
CPX_PARAM_EPINT = 0.0
CPX_PARAM_EPGAP = 1e-9
CPX_PARAM_EPRHS = 1e-9

[solver_params.dcglp]
solver = "CPLEX"
CPX_PARAM_EPINT = 0.0
CPX_PARAM_EPGAP = 1e-9
CPX_PARAM_EPRHS = 1e-9


# Cut strategy configuration
[cut_strategy]
type = "DISJUNCTIVE_CUT"
base_cut_strategy = "FAT_KNAPSACK_CUT"
norm_type = "L1NORM"
cut_strengthening = "PURE_DISJUNCTION"
use_two_sided_cuts = true
include_master_cuts = true
reuse_dcglp = false
verbose = false

# now we use linear relaxation UB for the master problem
# params.time_limit = 600