using Documenter
using BendersX

println("Module loaded. Exports:", names(BendersX, all=false))
for n in names(BendersX, all=true)
    if isdefined(BendersX, n)
        obj = getfield(BendersX, n)
        has = Base.Docs.doc(obj) !== nothing
        if has
            println("DOC: ", n)
        end
    end
end

makedocs(
    sitename = "BendersX.jl",
    format = Documenter.HTML(),
    pages = [
        "Home" => "index.md",
        # "Tutorials" => "tutorial.md",
        "Tutorials" => [
            "Getting Started" => "tutorials/getting_started.md",
            "Swapping Oracles and Adjusting Their Behaviors" => "tutorials/oracles.md",
            "Swapping Environments and Adjusting Their Behaviors" => "tutorials/envs.md",
            "Examples" => "tutorials/examples.md"
        ],
        "User Guide" => "user_guide.md",
        # "References" => "references.md",
        # "API Reference" => Documenter.Autodocs.autogenerated(modules=[BendersX]),
        # "Examples" => "examples.md",
        # "Contributing" => "contrib.md",
        # "FAQ" => "faq.md",
        # "Architecture" => "architecture.md"
        # "Tutorial" => [
        #     "Data" => "Tutorial/data.md",
        #     "Modeling Interface" => "Tutorial/modeling.md",
        #     "Running Benders" => "Tutorial/envs.md",
        #     "Example - Capacitated Facility Location Problem (CFLP)" => "Tutorial/example.md",
        # ],
        "API" => "api.md",
    ],
    # sitelogo = "assets/logo.svg",
)