# ============================================================================
# GBC (Generalized Bound Constraints) Bound Type
# ============================================================================
@enum GBCBoundType begin
    UpperBound   # y ≤ f(x)
    LowerBound   # y ≥ f(x)
    Fixed   # y = f(x)
end

"""
Supertype for all Benders execution environments.

An environment owns the algorithmic control flow that orchestrates calls to
the master problem and one or more oracles. Concrete subtypes implement
different execution strategies, such as sequential cutting-plane loops or
callback-driven branch-and-bound.

See also: [`AbstractBendersSeq`](@ref), [`AbstractBendersBnB`](@ref)
"""
abstract type AbstractBendersEnv end
"""
    AbstractMaster

Supertype for Benders master problems.

A master owns the optimization model seen by the environment, accepts cuts
generated by oracles, and provides candidate solutions for oracle evaluation.

See also: [`AbstractBendersEnv`](@ref), [`AbstractOracle`](@ref), [`Master`](@ref)
"""
abstract type AbstractMaster end
"""
Any concrete subtype of `AbstractOracle` must have a field `param<:AbstractOracleParam` containing adjustable parameters that affect the oracle's behavior.
The type of `param` can be BasicOracleParam when there is no oracle-specific adjustable parameter.

Subtypes should implement `generate_cuts` to return separating hyperplanes based on the given candidate solutions.
"""
abstract type AbstractOracle end
"""
Supertype for parameter containers attached to concrete oracle types.

Oracle parameters collect the tolerance values and strategy switches that may
be adjusted without rebuilding the oracle object itself. Concrete oracles
typically store one field `param <: AbstractOracleParam`.

See also: [`BasicOracleParam`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractOracleParam end
"""
    AbstractData

Supertype for user-defined problem data.

Concrete subtypes store the coefficients, dimensions, and any scenario data
needed to build the master and subproblem models. Users are expected to define
their own `AbstractData` subtype for each application.

See also: [`customize_master_model!`](@ref), [`customize_sub_model!`](@ref)
"""
abstract type AbstractData end

"""
Supertype for sequential Benders environments.

Sequential environments repeatedly solve the master problem, query an oracle at
the current candidate point, add cuts, and continue until a termination rule is
met.

See also: [`BendersSeq`](@ref), [`BendersSeqInOut`](@ref), [`SpecializedBendersSeq`](@ref)
"""
abstract type AbstractBendersSeq <: AbstractBendersEnv end
"""
Supertype for callback-based branch-and-bound Benders environments.

These environments integrate Benders cut generation into the MIP solver's
branch-and-bound process via lazy constraints, user cuts, and optional root
preprocessing.

See also: [`BendersBnB`](@ref)
"""
abstract type AbstractBendersBnB <: AbstractBendersEnv end

# ============================================================================
# Termination Status of Benders Decomposition
# ============================================================================
abstract type TerminationStatus end
struct NotSolved <: TerminationStatus end
struct TimeLimit <: TerminationStatus end
struct Optimal <: TerminationStatus end
struct InfeasibleOrNumericalIssue <: TerminationStatus end

# ============================================================================
# Error Exceptions
# ============================================================================
struct TimeLimitException <: Exception 
    msg::String
end
struct UnexpectedModelStatusException <: Exception 
    msg::String
end
struct AlgorithmException <: Exception 
    msg::String
end
struct UndefError <: Exception 
    msg::String
end
struct UnsupportedModelException <: Exception 
    msg::String
end

# ============================================================================
# Normalization type for CGLP
# ============================================================================
abstract type AbstractNorm end
struct StandardNorm <: AbstractNorm end
"""
    LpNorm(p::Float64)

Lp normalization used by the disjunctive cut generating LP.

The value `p` specifies the norm order used in normalization constraints for
the DCGLP. Typical choices are `1.0`, `2.0`, and `Inf`.

See also: [`SplitOracleParam`](@ref), `add_normalization_constraint`
"""
mutable struct LpNorm <: AbstractNorm
    p::Float64
    function LpNorm(p::Float64)
        new(p)
    end
end

# ============================================================================
# Rules for constructing a split set
# ============================================================================
abstract type SplitIndexSelectionRule end
abstract type SimpleSplit <: SplitIndexSelectionRule end
struct RandomFractional <: SimpleSplit end
struct MostFractional <: SimpleSplit end
struct LargestFractional <: SimpleSplit end

# ============================================================================
# Rules for appending pre-found disjunctive cuts to dcglp
# ============================================================================
abstract type DisjunctiveCutsAppendRule end
struct NoDisjunctiveCuts <: DisjunctiveCutsAppendRule end
struct AllDisjunctiveCuts <: DisjunctiveCutsAppendRule end
struct DisjunctiveCutsSmallerIndices <: DisjunctiveCutsAppendRule end
