
"""
    AbstractBendersEnv

Abstract supertype for Benders decomposition execution environments.

An `AbstractBendersEnv` coordinates the interaction between a master module and
one or more oracles, and defines the overall algorithmic structure (e.g.,
sequential or branch-and-bound execution, stopping criteria, logging, and scheduling).

Concrete subtypes typically:
- Own a master module and one or more oracles
- Control the Benders iteration loop
- Manage convergence checks and logging

See also: [`AbstractMaster`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractBendersEnv end

"""
    AbstractMaster

Abstract supertype for Benders master problems.

An `AbstractMaster` encapsulates the master optimization model in a Benders
decomposition.

Concrete subtypes are responsible for:
- Accepting cuts generated by oracles
- Providing candidate solutions to the environment
- Solving and updating the master model

See also: [`AbstractBendersEnv`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractMaster end

"""
    AbstractOracle

Abstract supertype for Benders oracles.

An `AbstractOracle` generates separating hyperplanes (Benders cuts) based on
candidate solutions provided by the environment.

## Interface Requirements
Any concrete subtype of `AbstractOracle` must:
- Contain a field `param <: AbstractOracleParam` storing adjustable parameters
  that control the oracle’s behavior. When no oracle-specific parameters are
  needed, [`BasicOracleParam`](@ref) may be used.
- Implement [`generate_cuts`](@ref), which computes violated cuts for a given
  candidate solution.

The `generate_cuts` method should return hyperplanes that are valid for the
master problem and separate infeasible or suboptimal candidate solutions.

See also: [`AbstractOracleParam`](@ref), [`generate_cuts`](@ref)
"""
abstract type AbstractOracle end

"""
    AbstractOracleParam

Abstract supertype for oracle parameter containers.

Subtypes of `AbstractOracleParam` define numerical tolerances
and other adjustable parameters that affect oracle behavior during cut
generation.

See also: [`AbstractOracle`](@ref)
"""
abstract type AbstractOracleParam end

"""
    AbstractData

Abstract supertype for user-defined problem data.

`AbstractData` represents immutable or semi-immutable data required to build
the master and subproblem models, such as coefficients, dimensions, and scenario
information.

Users are expected to define concrete subtypes of `AbstractData` tailored to
their specific application and pass them to BendersX constructors.

See also: [`AbstractMaster`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractData end

"""
    AbstractBendersSeq <: AbstractBendersEnv

Abstract supertype for **sequential** Benders decomposition environments.

An `AbstractBendersSeq` executes the Benders algorithm in a
serial fashion, solving the master problem to optimality and invoking oracles sequentially at
each iteration.

Concrete subtypes typically:
- Solve the master problem one iteration at a time
- Call oracles sequentially to generate cuts
- Update the master and check convergence before proceeding

See also: [`AbstractBendersEnv`](@ref), [`AbstractBendersBnB`](@ref)
"""
abstract type AbstractBendersSeq <: AbstractBendersEnv end

"""
    AbstractBendersBnB <: AbstractBendersEnv

Abstract supertype for **branch-and-bound**-based Benders environments.

An `AbstractBendersBnB` integrates Benders decomposition within a branch-and-
bound framework, typically to handle integer or mixed-integer master problems.

Concrete subtypes are expected to:
- Define preprocessing logic
- Provide lazy constraint callbacks for integer-feasible nodes
- Provide user constraint callbacks for fractional nodes

See also: [`AbstractBendersEnv`](@ref), [`AbstractBendersSeq`](@ref)
"""
abstract type AbstractBendersBnB <: AbstractBendersEnv end

# ============================================================================
# Termination Status of Benders Decomposition
# ============================================================================
abstract type TerminationStatus end
struct NotSolved <: TerminationStatus end
struct TimeLimit <: TerminationStatus end
struct Optimal <: TerminationStatus end
struct InfeasibleOrNumericalIssue <: TerminationStatus end

# ============================================================================
# Error Exceptions
# ============================================================================
struct TimeLimitException <: Exception 
    msg::String
end
struct UnexpectedModelStatusException <: Exception 
    msg::String
end
struct AlgorithmException <: Exception 
    msg::String
end
struct UndefError <: Exception 
    msg::String
end

# ============================================================================
# Normalization type for CGLP
# ============================================================================
abstract type AbstractNorm end
struct StandardNorm <: AbstractNorm end
mutable struct LpNorm <: AbstractNorm 
    p::Float64
    function LpNorm(p::Float64)
        new(p)
    end
end

# ============================================================================
# Rules for constructing a split set # To-Do: change SplitIndexSelectionRule to SplitSelectionRule
# ============================================================================
abstract type SplitIndexSelectionRule end
abstract type SimpleSplit <: SplitIndexSelectionRule end
struct RandomFractional <: SimpleSplit end
struct MostFractional <: SimpleSplit end
struct LargestFractional <: SimpleSplit end

# ============================================================================
# Rules for appending pre-found disjunctive cuts to dcglp
# ============================================================================
abstract type DisjunctiveCutsAppendRule end
struct NoDisjunctiveCuts <: DisjunctiveCutsAppendRule end
struct AllDisjunctiveCuts <: DisjunctiveCutsAppendRule end
struct DisjunctiveCutsSmallerIndices <: DisjunctiveCutsAppendRule end




