# ============================================================================
# GBC (Generalized Bound Constraints) Bound Type
# ============================================================================
"""
    GBCBoundType

Enumeration describing the sense of a generalized bound constraint returned by
a subproblem model-update function.

- `UpperBound`: interpret the relation as `lhs <= rhs`
- `LowerBound`: interpret the relation as `lhs >= rhs`
- `Fixed`: interpret the relation as `lhs == rhs`
"""
@enum GBCBoundType begin
    UpperBound   # y ≤ f(x)
    LowerBound   # y ≥ f(x)
    Fixed   # y = f(x)
end

"""
Supertype for all Benders execution environments.

An environment owns the algorithmic control flow that orchestrates calls to
the master problem and one or more oracles. Concrete subtypes implement
different execution strategies, such as sequential cutting-plane loops or
callback-driven branch-and-bound.

See also: [`AbstractBendersSeq`](@ref), [`AbstractBendersBnB`](@ref)
"""
abstract type AbstractBendersEnv end
"""
    AbstractMaster

Supertype for Benders master problems.

A master owns the optimization model seen by the environment, accepts cuts
generated by oracles, and provides candidate solutions for oracle evaluation.

See also: [`AbstractBendersEnv`](@ref), [`AbstractOracle`](@ref), [`Master`](@ref)
"""
abstract type AbstractMaster end
"""
Any concrete subtype of `AbstractOracle` must have a field `param<:AbstractOracleParam` containing adjustable parameters that affect the oracle's behavior.
The type of `param` can be BasicOracleParam when there is no oracle-specific adjustable parameter.

Subtypes should implement `generate_cuts` to return separating hyperplanes based on the given candidate solutions.
"""
abstract type AbstractOracle end
"""
Supertype for parameter containers attached to concrete oracle types.

Oracle parameters collect the tolerance values and strategy switches that may
be adjusted without rebuilding the oracle object itself. Concrete oracles
typically store one field `param <: AbstractOracleParam`.

See also: [`BasicOracleParam`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractOracleParam end
"""
    AbstractData

Supertype for user-defined problem data.

Concrete subtypes store the coefficients, dimensions, and any scenario data
needed to build the master and subproblem models. Users are expected to define
their own `AbstractData` subtype for each application.

See also: [`Master`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractData end

"""
Supertype for sequential Benders environments.

Sequential environments repeatedly solve the master problem, query an oracle at
the current candidate point, add cuts, and continue until a termination rule is
met.

See also: [`BendersSeq`](@ref), [`BendersSeqInOut`](@ref), [`SpecializedBendersSeq`](@ref)
"""
abstract type AbstractBendersSeq <: AbstractBendersEnv end
"""
Supertype for callback-based branch-and-bound Benders environments.

These environments integrate Benders cut generation into the MIP solver's
branch-and-bound process via lazy constraints, user cuts, and optional root
preprocessing.

See also: [`BendersBnB`](@ref)
"""
abstract type AbstractBendersBnB <: AbstractBendersEnv end

# ============================================================================
# Termination Status of Benders Decomposition
# ============================================================================
"""
    TerminationStatus

Abstract supertype for high-level solve statuses returned by Benders
environments.
"""
abstract type TerminationStatus end
"""Solve has not completed yet."""
struct NotSolved <: TerminationStatus end
"""Solve terminated because the configured time limit was reached."""
struct TimeLimit <: TerminationStatus end
"""Solve terminated normally with an optimal solution or bound."""
struct Optimal <: TerminationStatus end
"""Solve terminated because of infeasibility or a numerical issue."""
struct InfeasibleOrNumericalIssue <: TerminationStatus end

# ============================================================================
# Error Exceptions
# ============================================================================
struct TimeLimitException <: Exception 
    msg::String
end
struct UnexpectedModelStatusException <: Exception 
    msg::String
end
struct AlgorithmException <: Exception 
    msg::String
end
struct UndefError <: Exception 
    msg::String
end
struct UnsupportedModelException <: Exception 
    msg::String
end

# ============================================================================
# Normalization type for CGLP
# ============================================================================
abstract type AbstractNorm end
struct StandardNorm <: AbstractNorm end
"""
    LpNorm(p::Float64)

Lp normalization used by the disjunctive cut generating LP.

The value `p` specifies the norm order used in normalization constraints for
the DCGLP. Typical choices are `1.0`, `2.0`, and `Inf`.

See also: [`DistanceNormOracleParam`](@ref), `add_normalization_constraint`
"""
mutable struct LpNorm <: AbstractNorm
    p::Float64
    function LpNorm(p::Float64)
        new(p)
    end
end

# ============================================================================
# Rules for constructing a split set
# ============================================================================
"""
    SplitIndexSelectionRule

Abstract supertype for rules that choose which fractional master variable is
used to form a split disjunction in disjunctive DCGLP oracles.
"""
abstract type SplitIndexSelectionRule end
abstract type SimpleSplit <: SplitIndexSelectionRule end
"""Select a fractional split index at random."""
struct RandomFractional <: SimpleSplit end
"""Select the split index with value closest to 0.5."""
struct MostFractional <: SimpleSplit end
"""Select the largest-index fractional master variable."""
struct LargestFractional <: SimpleSplit end

# ============================================================================
# Rules for appending pre-found disjunctive cuts to dcglp
# ============================================================================
"""
    DisjunctiveCutsAppendRule

Abstract supertype for policies that decide how previously generated
disjunctive cuts are reused inside the DCGLP solved by disjunctive oracles.
"""
abstract type DisjunctiveCutsAppendRule end
"""Do not reuse previously generated disjunctive cuts."""
struct NoDisjunctiveCuts <: DisjunctiveCutsAppendRule end
"""Reuse all previously generated disjunctive cuts."""
struct AllDisjunctiveCuts <: DisjunctiveCutsAppendRule end
"""Reuse only cuts associated with smaller split indices."""
struct DisjunctiveCutsSmallerIndices <: DisjunctiveCutsAppendRule end
