# ============================================================================
# Cut-generating oracles
# ============================================================================

# ---------------------------------------------------------------------------- 
# Common interface 
# ----------------------------------------------------------------------------
"""
    generate_cuts(
        oracle::AbstractOracle,
        x_value::Vector{Float64},
        t_value::Vector{Float64};
        tol_normalize = 1.0,
        time_limit = 3600,
    )

Generate cuts for a candidate master solution.

Concrete [`AbstractOracle`](@ref) types implement this method to evaluate the candidate point and, when necessary, generate valid inequalities separating it from the oracle's associated feasible region, denoted by `L`. For typical oracles, `L` is the set defined by all Benders cuts; for disjunctive oracles, `L` is the corresponding disjunctive set.

# Arguments

- `oracle::AbstractOracle`: Oracle used to evaluate and separate the candidate solution.
- `x_value`: Candidate values of the master variables `x`.
- `t_value`: Candidate values of the auxiliary variables `t`.
- `tol_normalize`: Normalization factor used during cut generation (default: 1.0). This parameter is used internally by disjunctive oracles and typically does not need to be specified by users.
- `time_limit`: Maximum time allowed for the oracle evaluation, in seconds.

# Returns

A tuple `(is_in_L, hyperplanes, sub_obj_vals)` where:

- `is_in_L::Bool`: Whether the candidate point belongs to `L`.
- `hyperplanes::Vector{Hyperplane}`: Valid inequalities generated by the oracle.
- `sub_obj_vals::Vector{Float64}`: Subproblem objective values used for updating the master upper bound. Values may be `NaN` when no meaningful objective is available.

Throws an error if `generate_cuts` is not implemented for a concrete subtype of `AbstractOracle`
"""
function generate_cuts(oracle::AbstractOracle, x_value::Vector{Float64}, t_value::Vector{Float64}; tol_normalize = 1.0, time_limit = 3600)
    throw(UndefError("update generate_cuts for $(typeof(oracle))"))
end

"""
    BasicOracleParam <: AbstractOracleParam

Basic parameters for Benders oracles.

# Fields

- `rtol` and `atol` determine the threshold for identifying a violation. Specifically, a violation is detected when `sub_obj_val` >= `t_value` * (1 + `rtol`) + `atol` in the finite-optimal subproblem case.
- `zero_tol` specifies the threshold below which a value is considered zero.

The default values are `rtol = 1e-9`, `atol = 0.0`, and `zero_tol = 1e-9`.
"""
struct BasicOracleParam <: AbstractOracleParam
    rtol::Float64
    atol::Float64
    zero_tol::Float64

    function BasicOracleParam(; rtol = 1e-9, atol = 0.0, zero_tol = 1e-9)
        new(rtol, atol, zero_tol)
    end
end

include("oracleTypical.jl")
include("oracleDisjunctive.jl")
